apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      environment: develop
  template:
    metadata:
      labels:
        app: frontend
        environment: develop
    spec:
      containers:
        - name: nextjs
          image: 049228899769.dkr.ecr.ap-northeast-3.amazonaws.com/frontend_kiibase:beta-0.1.3
          ports:
            - containerPort: 3000
