apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
    environments: develop
data:
  API_HOST: https://base.jenyen-uat.kiitzu.ninja/api
  STORAGE_HOST: https://base.jenyen-uat.kiitzu.ninja/storage
