apiVersion: v1
kind: Pod
metadata:
  name: kiibase
  labels:
    app: frontend
    environment: develop
spec:
  containers:
    - name: kiibase
      image: FIXME
      ports:
        - containerPort: 3000
      env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: API_HOST
        - name: STORAGE_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: STORAGE_HOST
